import {
  testAnswerUserBoundary,
  testAttemptSnapshotVersioning,
  testBlueprintAllocation,
  testInvalidQuestionStatuses,
  testQuestionSelection,
  testScoring,
} from './examEngine.test';
import { testSubjectProgressSemantics, testTopicProgress } from './progress.test';
import {
  testActiveSubjectsHaveRequirements,
  testBlueprintSums,
  testChapterThreeSectionsAreRepresented,
  testLawAndGeneralAdviceAreDistinguishable,
  testOfficialSubjectCounts,
  testRequirementsHaveSourceSubjectTopicAndReference,
  testStableKeysAreUnique,
  testTwoMainExamsExist,
} from './curriculum.test';
import {
  testD2TaxiLawLessonOutlinesCoverRequestedTopics,
  testD2TaxiLawSourceMappingsAreExplicitAndLegal,
  testD2TaxiLawUnresolvedMappingsAreMarked,
  testEveryD2TaxiLawRequirementHasSourceMapping,
} from './d2TaxiLawSources.test';
import {
  testD2TaxiLawCheckpointsUseFifteenPublishedQuestions,
  testD2TaxiLawFactsAreVerifiedAndSourced,
  testD2TaxiLawLessonsCoverEveryPublishedTopic,
  testD2TaxiLawQuestionsHaveFullTraceability,
  testD2TaxiLawRepositoryPublishesRequestedTopics,
} from './d2TaxiLawContent.test';
import {
  testD2FullMockExamBlueprintMatchesOfficialScoring,
  testD2FullMockQuestionVersionsFreezeAtAttemptStart,
  testD2StudyStateKeepsCompletionMasteryAndMockPerformanceSeparate,
  testD2TrafficLawFactsAreVerifiedAndSourced,
  testD2TrafficLawLessonsMapToRequirementsFactsAndVisualMetadata,
  testD2TrafficLawQuestionsHaveTraceabilityChain,
  testD2TrafficLawSourcesAreAuthoritative,
  testD2TrafficLawSubjectCheckpointSamplesBroadly,
  testD2TrafficLawTopicCheckpointsUseEligibleQuestions,
  testD2TrafficLawVisualDependentContentIsMarked,
  testEveryD2TrafficLawRequirementHasSourceMapping,
} from './d2TrafficLawContent.test';
import {
  testD2QualityGateHasNoDuplicateAnswerSets,
  testD2QualityGateHasNoDuplicateQuestionText,
  testD2QualityGateHasNoDuplicateStableKeys,
  testD2QualityGateMockAttemptHasNoDuplicateQuestions,
  testD2QualityGatePublishedQuestionsHaveExplanations,
  testD2QualityGatePublishedQuestionsHaveTraceability,
  testD2QualityGatePublishedVisualQuestionsRequireAssets,
} from './d2QualityGate.test';
import {
  testD1NavigationFactsAreVerifiedAndSourced,
  testD1NavigationLessonsHaveTraceabilityAndMapMetadata,
  testD1NavigationMapDependentQuestionsCarryMapMetadata,
  testD1NavigationPluggaIntegrationAndMobileFlow,
  testD1NavigationQuestionCompetenciesMatchRequirements,
  testD1NavigationQuestionsHaveFullTraceability,
  testD1NavigationRequirementsHaveSourceMappings,
  testD1NavigationTopicAndSubjectCheckpointsSelectEligibleQuestions,
} from './d1NavigationContent.test';
import {
  testD1EcoDrivingFactsAreVerifiedAndSourced,
  testD1EcoDrivingLessonsHaveTraceability,
  testD1EcoDrivingPluggaIntegrationAndScope,
  testD1EcoDrivingQuestionBankHasNoDuplicates,
  testD1EcoDrivingQuestionTypesMatchCompetencies,
  testD1EcoDrivingQuestionsHaveFullTraceability,
  testD1EcoDrivingRequirementsHaveSourceMappings,
  testD1EcoDrivingTopicAndSubjectCheckpointsSelectEligibleQuestions,
} from './d1EcoDrivingContent.test';
import {
  testD1EnvironmentCrossSubjectQuestionsDifferFromEcoDriving,
  testD1EnvironmentFactsAreVerifiedAndSourced,
  testD1EnvironmentLessonsHaveTraceabilityAndVisualMetadata,
  testD1EnvironmentPluggaIntegrationAndScope,
  testD1EnvironmentQuestionBankHasNoDuplicates,
  testD1EnvironmentQuestionTypesMatchCompetencies,
  testD1EnvironmentQuestionsHaveFullTraceability,
  testD1EnvironmentRequirementsHaveSourceMappings,
  testD1EnvironmentTopicAndSubjectCheckpointsSelectEligibleQuestions,
} from './d1EnvironmentContent.test';
import {
  testD1VehicleKnowledgeCrossSubjectDuplicateGate,
  testD1VehicleKnowledgeFactsAreVerifiedAndSourced,
  testD1VehicleKnowledgeLessonsHaveTraceabilityAndVisualAssets,
  testD1VehicleKnowledgePluggaIntegrationAndScope,
  testD1VehicleKnowledgeQuestionBankHasNoDuplicates,
  testD1VehicleKnowledgeQuestionTypesMatchCompetencies,
  testD1VehicleKnowledgeQuestionsHaveFullTraceabilityAndVisualAssets,
  testD1VehicleKnowledgeRequirementsHaveSourceMappings,
  testD1VehicleKnowledgeTopicAndSubjectCheckpointsSelectEligibleQuestions,
  testD1VehicleKnowledgeVisualManifestIsStructured,
} from './d1VehicleKnowledgeContent.test';
import {
  testVilotiderCalculationQuestionsUseCalculationRequirement,
  testVilotiderCheckpointSelectionAndVersionFreeze,
  testVilotiderFactsAreVerifiedAndSourced,
  testVilotiderLessonsHaveRequirementAndFactLinks,
  testVilotiderQuestionsHaveFullTraceability,
} from './vilotiderContent.test';
import {
  testMobileFlowCheckpointUsesFifteenQuestions,
  testMobileFlowCompletedAttemptCannotBeAltered,
  testMobileFlowFirstIncompleteLesson,
  testMobileFlowLessonCompletionPersistence,
  testMobileFlowLessonOrdering,
  testMobileFlowQuestionVersionsRemainFrozen,
  testMobileFlowResultsAreDeterministic,
  testMobileFlowTopicProgressDerivation,
} from './mobileLearningFlow.test';

const tests = [
  ['blueprint allocation', testBlueprintAllocation],
  ['question selection', testQuestionSelection],
  ['invalid question statuses', testInvalidQuestionStatuses],
  ['attempt snapshot versioning', testAttemptSnapshotVersioning],
  ['scoring', testScoring],
  ['answer user boundary', testAnswerUserBoundary],
  ['topic progress', testTopicProgress],
  ['subject progress semantics', testSubjectProgressSemantics],
  ['curriculum has exactly two exams', testTwoMainExamsExist],
  ['curriculum has official subject counts', testOfficialSubjectCounts],
  ['curriculum blueprint sums', testBlueprintSums],
  ['active subjects have requirements', testActiveSubjectsHaveRequirements],
  ['requirements have source subject topic reference', testRequirementsHaveSourceSubjectTopicAndReference],
  ['law and general advice are distinguishable', testLawAndGeneralAdviceAreDistinguishable],
  ['stable keys are unique', testStableKeysAreUnique],
  ['chapter 3 sections are represented', testChapterThreeSectionsAreRepresented],
  ['D2 taxi law requirements have source mappings', testEveryD2TaxiLawRequirementHasSourceMapping],
  ['D2 taxi law source mappings are explicit and legal', testD2TaxiLawSourceMappingsAreExplicitAndLegal],
  ['D2 taxi law unresolved mappings are marked', testD2TaxiLawUnresolvedMappingsAreMarked],
  ['D2 taxi law lesson outlines cover requested topics', testD2TaxiLawLessonOutlinesCoverRequestedTopics],
  ['D2 taxi law repository publishes requested topics', testD2TaxiLawRepositoryPublishesRequestedTopics],
  ['D2 taxi law facts are verified and sourced', testD2TaxiLawFactsAreVerifiedAndSourced],
  ['D2 taxi law lessons cover every published topic', testD2TaxiLawLessonsCoverEveryPublishedTopic],
  ['D2 taxi law questions have full traceability', testD2TaxiLawQuestionsHaveFullTraceability],
  ['D2 taxi law checkpoints use fifteen published questions', testD2TaxiLawCheckpointsUseFifteenPublishedQuestions],
  ['D2 traffic law requirements have source mappings', testEveryD2TrafficLawRequirementHasSourceMapping],
  ['D2 traffic law sources are authoritative', testD2TrafficLawSourcesAreAuthoritative],
  ['D2 traffic law facts are verified and sourced', testD2TrafficLawFactsAreVerifiedAndSourced],
  ['D2 traffic law lessons map to requirements, facts and visuals', testD2TrafficLawLessonsMapToRequirementsFactsAndVisualMetadata],
  ['D2 traffic law questions have traceability chain', testD2TrafficLawQuestionsHaveTraceabilityChain],
  ['D2 traffic law visual-dependent content is marked', testD2TrafficLawVisualDependentContentIsMarked],
  ['D2 traffic law topic checkpoints use eligible questions', testD2TrafficLawTopicCheckpointsUseEligibleQuestions],
  ['D2 traffic law subject checkpoint samples broadly', testD2TrafficLawSubjectCheckpointSamplesBroadly],
  ['D2 full mock exam blueprint matches official scoring', testD2FullMockExamBlueprintMatchesOfficialScoring],
  ['D2 full mock question versions freeze at attempt start', testD2FullMockQuestionVersionsFreezeAtAttemptStart],
  ['D2 study state keeps completion mastery and mock performance separate', testD2StudyStateKeepsCompletionMasteryAndMockPerformanceSeparate],
  ['D2 quality gate has no duplicate stable keys', testD2QualityGateHasNoDuplicateStableKeys],
  ['D2 quality gate has no duplicate question text', testD2QualityGateHasNoDuplicateQuestionText],
  ['D2 quality gate has no duplicate answer sets', testD2QualityGateHasNoDuplicateAnswerSets],
  ['D2 quality gate published visual questions require assets', testD2QualityGatePublishedVisualQuestionsRequireAssets],
  ['D2 quality gate published questions have explanations', testD2QualityGatePublishedQuestionsHaveExplanations],
  ['D2 quality gate published questions have traceability', testD2QualityGatePublishedQuestionsHaveTraceability],
  ['D2 quality gate mock attempt has no duplicate questions', testD2QualityGateMockAttemptHasNoDuplicateQuestions],
  ['D1 navigation requirements have source mappings', testD1NavigationRequirementsHaveSourceMappings],
  ['D1 navigation facts are verified and sourced', testD1NavigationFactsAreVerifiedAndSourced],
  ['D1 navigation lessons have traceability and map metadata', testD1NavigationLessonsHaveTraceabilityAndMapMetadata],
  ['D1 navigation questions have full traceability', testD1NavigationQuestionsHaveFullTraceability],
  ['D1 navigation map-dependent questions carry map metadata', testD1NavigationMapDependentQuestionsCarryMapMetadata],
  ['D1 navigation question competencies match requirements', testD1NavigationQuestionCompetenciesMatchRequirements],
  ['D1 navigation topic and subject checkpoints select eligible questions', testD1NavigationTopicAndSubjectCheckpointsSelectEligibleQuestions],
  ['D1 navigation Plugga integration and mobile flow', testD1NavigationPluggaIntegrationAndMobileFlow],
  ['D1 eco-driving requirements have source mappings', testD1EcoDrivingRequirementsHaveSourceMappings],
  ['D1 eco-driving facts are verified and sourced', testD1EcoDrivingFactsAreVerifiedAndSourced],
  ['D1 eco-driving lessons have traceability', testD1EcoDrivingLessonsHaveTraceability],
  ['D1 eco-driving questions have full traceability', testD1EcoDrivingQuestionsHaveFullTraceability],
  ['D1 eco-driving question bank has no duplicates', testD1EcoDrivingQuestionBankHasNoDuplicates],
  ['D1 eco-driving question types match competencies', testD1EcoDrivingQuestionTypesMatchCompetencies],
  ['D1 eco-driving topic and subject checkpoints select eligible questions', testD1EcoDrivingTopicAndSubjectCheckpointsSelectEligibleQuestions],
  ['D1 eco-driving Plugga integration and scope', testD1EcoDrivingPluggaIntegrationAndScope],
  ['D1 environment requirements have source mappings', testD1EnvironmentRequirementsHaveSourceMappings],
  ['D1 environment facts are verified and sourced', testD1EnvironmentFactsAreVerifiedAndSourced],
  ['D1 environment lessons have traceability and visual metadata', testD1EnvironmentLessonsHaveTraceabilityAndVisualMetadata],
  ['D1 environment questions have full traceability', testD1EnvironmentQuestionsHaveFullTraceability],
  ['D1 environment question bank has no duplicates', testD1EnvironmentQuestionBankHasNoDuplicates],
  ['D1 environment question types match competencies', testD1EnvironmentQuestionTypesMatchCompetencies],
  ['D1 environment cross-subject questions differ from eco-driving', testD1EnvironmentCrossSubjectQuestionsDifferFromEcoDriving],
  ['D1 environment topic and subject checkpoints select eligible questions', testD1EnvironmentTopicAndSubjectCheckpointsSelectEligibleQuestions],
  ['D1 environment Plugga integration and scope', testD1EnvironmentPluggaIntegrationAndScope],
  ['D1 vehicle knowledge requirements have source mappings', testD1VehicleKnowledgeRequirementsHaveSourceMappings],
  ['D1 vehicle knowledge facts are verified and sourced', testD1VehicleKnowledgeFactsAreVerifiedAndSourced],
  ['D1 vehicle knowledge lessons have traceability and visual assets', testD1VehicleKnowledgeLessonsHaveTraceabilityAndVisualAssets],
  ['D1 vehicle knowledge visual manifest is structured', testD1VehicleKnowledgeVisualManifestIsStructured],
  ['D1 vehicle knowledge questions have full traceability and visual assets', testD1VehicleKnowledgeQuestionsHaveFullTraceabilityAndVisualAssets],
  ['D1 vehicle knowledge question bank has no duplicates', testD1VehicleKnowledgeQuestionBankHasNoDuplicates],
  ['D1 vehicle knowledge question types match competencies', testD1VehicleKnowledgeQuestionTypesMatchCompetencies],
  ['D1 vehicle knowledge cross-subject duplicate gate', testD1VehicleKnowledgeCrossSubjectDuplicateGate],
  ['D1 vehicle knowledge topic and subject checkpoints select eligible questions', testD1VehicleKnowledgeTopicAndSubjectCheckpointsSelectEligibleQuestions],
  ['D1 vehicle knowledge Plugga integration and scope', testD1VehicleKnowledgePluggaIntegrationAndScope],
  ['Vilotider facts are verified and sourced', testVilotiderFactsAreVerifiedAndSourced],
  ['Vilotider lessons have requirement and fact links', testVilotiderLessonsHaveRequirementAndFactLinks],
  ['Vilotider questions have full traceability', testVilotiderQuestionsHaveFullTraceability],
  ['Vilotider calculation questions use calculation requirement', testVilotiderCalculationQuestionsUseCalculationRequirement],
  ['Vilotider checkpoint selection and version freeze', testVilotiderCheckpointSelectionAndVersionFreeze],
  ['mobile flow lesson ordering', testMobileFlowLessonOrdering],
  ['mobile flow first incomplete lesson', testMobileFlowFirstIncompleteLesson],
  ['mobile flow lesson completion persistence', testMobileFlowLessonCompletionPersistence],
  ['mobile flow topic progress derivation', testMobileFlowTopicProgressDerivation],
  ['mobile flow checkpoint uses fifteen questions', testMobileFlowCheckpointUsesFifteenQuestions],
  ['mobile flow question versions remain frozen', testMobileFlowQuestionVersionsRemainFrozen],
  ['mobile flow completed attempt cannot be altered', testMobileFlowCompletedAttemptCannotBeAltered],
  ['mobile flow results are deterministic', testMobileFlowResultsAreDeterministic],
] as const;

for (const [name, run] of tests) {
  run();
  console.log(`ok - ${name}`);
}
